apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.ingressController.name }}
    app.kubernetes.io/name: {{ .Values.ingressController.name }}
    app.kubernetes.io/instance: {{ .Values.ingressController.name }}
    app.kubernetes.io/version: 0.34.1
    app.kubernetes.io/component: controller
  name: {{ .Values.ingressController.name }}
  namespace: {{ .Release.Namespace }}
data:
