apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{ .Values.ingressController.name }}
    app.kubernetes.io/name: {{ .Values.ingressController.name }}
    app.kubernetes.io/instance: {{ .Values.ingressController.name }}
    app.kubernetes.io/version: 0.34.1
    app.kubernetes.io/component: controller
  name: {{ .Values.ingressController.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.ingressController.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.ingressController.name }}
    namespace: {{ .Release.Namespace }}
