{{- if .Values.backend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "qsc-nginx.serviceAccountName" . }}
  labels:
{{ include "qsc-nginx.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
