apiVersion: v1
kind: Service
metadata:
  name: {{ include "qsc-haproxy.fullname" . }}
  labels:
{{ include "qsc-haproxy.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "qsc-haproxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
