apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
    app.kubernetes.io/name: {{ .Values.service.name }}
    app.kubernetes.io/instance: {{ .Values.service.name }}
    app.kubernetes.io/version: 0.34.1
    app.kubernetes.io/component: controller
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: public
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app: {{ .Values.service.name }}
    app.kubernetes.io/name: {{ .Values.service.name }}
    app.kubernetes.io/instance: {{ .Values.service.name }}
    app.kubernetes.io/component: controller